export const TOOL_GENERATION_QUEUE = "tool-generation";

/** The six tools generated by the LLM. Audio overview is out of scope here. */
export const GENERATED_TOOL_KINDS = [
  "MINDMAP",
  "QUIZ",
  "CONCEPT_TABLE",
  "FLASHCARDS",
  "SUMMARY",
  "TIMELINE",
] as const;

export type ToolKind = (typeof GENERATED_TOOL_KINDS)[number];

export interface ToolGenerationJobData {
  notebookId: string;
  kind: ToolKind;
  userId: string;
  /** Snapshot of the generation revision at enqueue time. */
  revision: number;
}

export type GenerationStatus =
  | "IDLE"
  | "QUEUED"
  | "PROCESSING"
  | "READY"
  | "FAILED";

/** Payload of the `tool` SSE event, streamed over the notebook channel. */
export interface ToolGenerationEvent {
  notebookId: string;
  kind: ToolKind;
  status: GenerationStatus;
  /** 0-100 */
  progress: number;
  message?: string;
  error?: string;
  at: string;
}
